import type { CalendarEvent } from './AgendaCalendar.types'

export const DUMMY_AGENDA_EVENTS: CalendarEvent[] = [
  { id: 'ev-1', type: 'unavailability', date: '2026-07-28', allDay: true },
  { id: 'ev-2', type: 'unavailability', date: '2026-07-29', allDay: true },
  { id: 'ev-3', type: 'unavailability', date: '2026-07-30', allDay: true },
  { id: 'ev-4', type: 'unavailability', date: '2026-07-31', allDay: true },
  { id: 'ev-5', type: 'unavailability', date: '2026-08-01', allDay: true },
  { id: 'ev-6', type: 'unavailability', date: '2026-08-02', allDay: true },
  {
    id: 'ev-7',
    type: 'unavailability',
    date: '2026-08-03',
    allDay: false,
    timeRange: '08:00 - 14:00',
  },
  {
    id: 'ev-8',
    type: 'booking',
    date: '2026-08-04',
    time: '18:10 - 20:20',
    tailNumber: 'EC-EXL',
    pilotInCommand: 'Mike Murdoch [PIC]',
    flightLines: [
      'VTD01 - Precautionary landing. Reading maps of local area',
      'VTD02 - DM cross country flight',
    ],
  },
  {
    id: 'ev-9',
    type: 'unavailability',
    date: '2026-08-05',
    allDay: false,
    timeRange: '09:00 - 13:00',
  },
  {
    id: 'ev-10',
    type: 'booking',
    date: '2026-08-07',
    time: '13:10 - 15:20',
    tailNumber: 'EC-ERV',
    pilotInCommand: 'Jane Smith [PIC]',
    flightLines: ['VBD15 - Final check before solo flight'],
  },
  {
    id: 'ev-11',
    type: 'booking',
    date: '2026-08-12',
    time: '09:00 - 12:30',
    tailNumber: 'EC-KLM',
    pilotInCommand: 'SAMPLE PLACEHOLDER [PIC]',
    flightLines: [
      'VTD04 - Navigation exercise over the coastline with diversion practice',
      'VTD05 - Steep turns and stall recovery review',
      'VTD06 - Radio navigation using VOR and ADF, followed by a full instrument approach briefing',
      'VTD07 - Circuit practice, short and soft field landings',
    ],
    cancelled: true,
  },
  {
    id: 'ev-12',
    type: 'unavailability',
    date: '2026-08-19',
    allDay: false,
    timeRange: '07:00 - 10:00',
  },
  {
    id: 'ev-13',
    type: 'booking',
    date: '2026-09-02',
    time: '10:00 - 11:15',
    tailNumber: 'EC-FED',
    pilotInCommand: 'Jane Smith [PIC]',
    flightLines: ['VBD03 - Circuit consolidation'],
  },
]
