import type { Aircraft } from './AircraftDirectory.types'

export const DUMMY_FLEET: Aircraft[] = [
  {
    id: 'ac-1',
    arcid: 'EC-GV8',
    type: 'Aeroprakt A-22 LS',
    photoSrc: '/aircraft/aeroprakt-a-22-ls.webp',
  },
  {
    id: 'ac-2',
    arcid: 'EC-OKE',
    type: 'Airbus Helicopters AS355',
    photoSrc: '/aircraft/airbus-helicopters-as355.webp',
  },
  { id: 'ac-3', arcid: 'F-CEGG', type: 'Alexander Primary Glider' },
  {
    id: 'ac-4',
    arcid: 'EC-FRB',
    type: 'Aviat Aircraft Inc Pitts S-2B',
    photoSrc: '/aircraft/aviat-aircraft-inc-pitts-s-2b.webp',
  },
  {
    id: 'ac-5',
    arcid: 'EC-DKN',
    type: 'Cessna 152',
    photoSrc: '/aircraft/cessna-152.webp',
  },
  {
    id: 'ac-10',
    arcid: 'EC-JTJ',
    type: 'Cessna 172R',
    photoSrc: '/aircraft/cessna-172r.webp',
  },
  {
    id: 'ac-11',
    arcid: 'EC-JOB',
    type: 'Cessna 172S',
    photoSrc: '/aircraft/cessna-172s.webp',
  },
  {
    id: 'ac-13',
    arcid: 'EC-KOP',
    type: 'Cessna 182T',
    photoSrc: '/aircraft/cessna-182t.webp',
  },
  {
    id: 'ac-15',
    arcid: 'EC-CZZ',
    type: 'Cessna FR 172 J',
    photoSrc: '/aircraft/cessna-fr-172-j.webp',
  },
  {
    id: 'ac-19',
    arcid: 'EC-HIK',
    type: 'Cessna 172N',
    photoSrc: '/aircraft/cessna-172n.webp',
  },
  {
    id: 'ac-21',
    arcid: 'EC-KLM',
    type: 'Diamond DA40 NG',
    photoSrc: '/aircraft/diamond-da40-ng.webp',
  },
  {
    id: 'ac-23',
    arcid: 'EC-MNO',
    type: 'Diamond DA42 Twin Star',
    photoSrc: '/aircraft/diamond-da42-twin-star.webp',
  },
  {
    id: 'ac-24',
    arcid: 'EC-NOP',
    type: 'Piper PA-28-161 Warrior III',
    photoSrc: '/aircraft/piper-pa-28-161-warrior-iii.webp',
  },
  {
    id: 'ac-26',
    arcid: 'EC-PQR',
    type: 'Piper PA-28R-201 Arrow III',
    photoSrc: '/aircraft/piper-pa-28r-201-arrow-iii.webp',
  },
  {
    id: 'ac-27',
    arcid: 'EC-QRS',
    type: 'Piper PA-34-220T Seneca',
    photoSrc: '/aircraft/piper-pa-34-220t-seneca.webp',
  },
  {
    id: 'ac-28',
    arcid: 'EC-RST',
    type: 'Robin DR400/140B',
    photoSrc: '/aircraft/robin-dr400-140b.webp',
  },
  {
    id: 'ac-29',
    arcid: 'EC-STU',
    type: 'Robinson R22 Beta II',
    photoSrc: '/aircraft/robinson-r22-beta-ii.webp',
  },
  {
    id: 'ac-30',
    arcid: 'EC-TUV',
    type: 'Robinson R44 Raven II',
    photoSrc: '/aircraft/robinson-r44-raven-ii.webp',
  },
  {
    id: 'ac-31',
    arcid: 'EC-UVW',
    type: 'Tecnam P2002 Sierra',
    photoSrc: '/aircraft/tecnam-p2002-sierra.webp',
  },
  {
    id: 'ac-32',
    arcid: 'EC-VWX',
    type: 'Tecnam P2006T',
    photoSrc: '/aircraft/tecnam-p2006t.webp',
  },
  {
    id: 'ac-33',
    arcid: 'EC-WXY',
    type: 'Tecnam P2008 JC',
    photoSrc: '/aircraft/tecnam-p2008-jc.webp',
  },
  {
    id: 'ac-35',
    arcid: 'EC-ABC',
    type: 'Tecnam P92 Eaglet',
    photoSrc: '/aircraft/tecnam-p92-eaglet.webp',
  },
  {
    id: 'ac-36',
    arcid: 'EC-BCD',
    type: 'Zlin Z 242L',
    photoSrc: '/aircraft/zlin-z-242l.webp',
  },
  {
    id: 'ac-37',
    arcid: 'EC-CDE',
    type: 'Cirrus SR20',
    photoSrc: '/aircraft/cirrus-sr20.webp',
  },
  {
    id: 'ac-38',
    arcid: 'EC-DEF',
    type: 'Cirrus SR22',
    photoSrc: '/aircraft/cirrus-sr22.webp',
  },
  {
    id: 'ac-39',
    arcid: 'EC-EFG',
    type: 'Beechcraft F33A Bonanza',
    photoSrc: '/aircraft/beechcraft-f33a-bonanza.webp',
  },
  {
    id: 'ac-40',
    arcid: 'EC-FGH',
    type: 'Beechcraft A36 Bonanza',
    photoSrc: '/aircraft/beechcraft-a36-bonanza.webp',
  },
  {
    id: 'ac-41',
    arcid: 'EC-GHI',
    type: 'Socata TB-10 Tobago',
    photoSrc: '/aircraft/socata-tb-10-tobago.webp',
  },
  {
    id: 'ac-42',
    arcid: 'EC-HIJ',
    type: 'Socata TB-20 Trinidad',
    photoSrc: '/aircraft/socata-tb-20-trinidad.webp',
  },
  {
    id: 'ac-43',
    arcid: 'EC-IJK',
    type: 'Grob G 103 Twin Astir',
    photoSrc: '/aircraft/grob-g-103-twin-astir.webp',
  },
  {
    id: 'ac-44',
    arcid: 'EC-JKL',
    type: 'Schleicher ASK 21',
    photoSrc: '/aircraft/schleicher-ask-21.webp',
  },
  {
    id: 'ac-45',
    arcid: 'EC-KLL',
    type: 'Schempp-Hirth Discus CS',
    photoSrc: '/aircraft/schempp-hirth-discus-cs.webp',
  },
  {
    id: 'ac-46',
    arcid: 'EC-LMM',
    type: 'Rolladen-Schneider LS4',
    photoSrc: '/aircraft/rolladen-schneider-ls4.webp',
  },
  {
    id: 'ac-47',
    arcid: 'EC-MNN',
    type: 'Robin DR400/180 Regent',
    photoSrc: '/aircraft/robin-dr400-180-regent.webp',
  },
  {
    id: 'ac-48',
    arcid: 'EC-NOO',
    type: 'American Champion Decathlon',
    photoSrc: '/aircraft/american-champion-8kcab-decathlon.webp',
  },
  {
    id: 'ac-6',
    arcid: 'EC-DMC',
    type: 'Cessna 152',
    photoSrc: '/aircraft/cessna-152.webp',
  },
  {
    id: 'ac-12',
    arcid: 'EC-JPY',
    type: 'Cessna 172S',
    photoSrc: '/aircraft/cessna-172s.webp',
  },
  {
    id: 'ac-14',
    arcid: 'EC-KOQ',
    type: 'Cessna 182T',
    photoSrc: '/aircraft/cessna-182t.webp',
  },
  {
    id: 'ac-16',
    arcid: 'EC-DAE',
    type: 'Cessna FR 172 J',
    photoSrc: '/aircraft/cessna-fr-172-j.webp',
  },
  {
    id: 'ac-20',
    arcid: 'EC-IJL',
    type: 'Cessna 172N',
    photoSrc: '/aircraft/cessna-172n.webp',
  },
  {
    id: 'ac-22',
    arcid: 'EC-LMN',
    type: 'Diamond DA40 NG',
    photoSrc: '/aircraft/diamond-da40-ng.webp',
  },
  {
    id: 'ac-25',
    arcid: 'EC-OPQ',
    type: 'Piper PA-28-161 Warrior III',
    photoSrc: '/aircraft/piper-pa-28-161-warrior-iii.webp',
  },
  {
    id: 'ac-34',
    arcid: 'EC-XYZ',
    type: 'Tecnam P2008 JC',
    photoSrc: '/aircraft/tecnam-p2008-jc.webp',
  },
  {
    id: 'ac-7',
    arcid: 'EC-DRV',
    type: 'Cessna 152',
    photoSrc: '/aircraft/cessna-152.webp',
  },
  {
    id: 'ac-8',
    arcid: 'EC-ERV',
    type: 'Cessna 152',
    photoSrc: '/aircraft/cessna-152.webp',
  },
  {
    id: 'ac-9',
    arcid: 'EC-EXL',
    type: 'Cessna 152',
    photoSrc: '/aircraft/cessna-152.webp',
  },
  {
    id: 'ac-17',
    arcid: 'EC-FED',
    type: 'Cessna 152',
    photoSrc: '/aircraft/cessna-152.webp',
  },
  {
    id: 'ac-18',
    arcid: 'EC-GHT',
    type: 'Cessna 152',
    photoSrc: '/aircraft/cessna-152.webp',
  },
]
