import type { AvailabilityEntry } from './Availability.types'

export const DUMMY_AVAILABILITY_ENTRIES: AvailabilityEntry[] = [
  {
    id: 'avail-1',
    dateMode: 'range',
    fromDate: '27/08/2026',
    toDate: '30/08/2026',
    timeMode: 'between',
    startTime: '18:00',
    endTime: '21:00',
    recurrenceMode: 'everyday',
  },
  {
    id: 'avail-2',
    dateMode: 'range',
    fromDate: '17/08/2026',
    toDate: '19/08/2026',
    timeMode: 'allDay',
    recurrenceMode: 'days',
    recurrenceDays: ['mon', 'tue', 'wed'],
  },
  {
    id: 'avail-3',
    dateMode: 'range',
    fromDate: '10/08/2026',
    toDate: '16/08/2026',
    timeMode: 'between',
    startTime: '12:00',
    endTime: '15:00',
    recurrenceMode: 'everyday',
  },
  {
    id: 'avail-4',
    dateMode: 'range',
    fromDate: '03/08/2026',
    toDate: '09/08/2026',
    timeMode: 'between',
    startTime: '08:00',
    endTime: '21:00',
    recurrenceMode: 'everyday',
  },
  {
    id: 'avail-5',
    dateMode: 'range',
    fromDate: '31/07/2026',
    toDate: '02/08/2026',
    timeMode: 'allDay',
    recurrenceMode: 'everyday',
  },
]
