import type { Instructor, Student } from './RoleSwitcher.types'

export const DUMMY_INSTRUCTORS: Instructor[] = [
  {
    id: 'instructor-1',
    name: 'James Whitfield',
    initials: 'JW',
    color: 'var(--color-avatar-blue)',
    email: 'james.whitfield@example.com',
    phone: '+34 600 111 222',
    birthday: '8 September 1985',
    info: 'CFI · Since 2015',
    photoSrc: '/instructors/james-whitfield.webp',
  },
  {
    id: 'instructor-2',
    name: 'Kate Ashford',
    initials: 'KA',
    color: 'var(--color-avatar-pink)',
    email: 'kate.ashford@example.com',
    phone: '+34 600 222 333',
    birthday: '19 April 1990',
    info: 'CFI · Since 2019',
    photoSrc: '/instructors/kate-ashford.webp',
  },
]

export const DUMMY_STUDENTS: Student[] = [
  {
    id: 'student-1',
    name: 'Alex Moreau',
    initials: 'AM',
    color: 'var(--color-avatar-sky)',
    track: 'IR',
    email: 'alex.moreau@example.com',
    phone: '+34 600 234 567',
    birthday: '22 June 1998',
    info: 'IR online · Q3 2025',
  },
  {
    id: 'student-2',
    name: 'Jamie Torres',
    initials: 'JT',
    color: 'var(--color-avatar-lime)',
    track: 'PPL',
    email: 'jamie.torres@example.com',
    phone: '+34 600 123 456',
    birthday: '14 March 1994',
    info: 'PPL online · Q1 2025',
  },
  {
    id: 'student-3',
    name: 'Priya Shah',
    initials: 'PS',
    color: 'var(--color-avatar-amber)',
    track: 'CPL',
    email: 'priya.shah@example.com',
    phone: '+34 600 345 678',
    birthday: '5 November 1996',
    info: 'CPL online · Q2 2025',
  },
  {
    id: 'student-4',
    name: 'Noah Becker',
    initials: 'NB',
    color: 'var(--color-avatar-purple)',
    track: 'PPL',
    email: 'noah.becker@example.com',
    phone: '+34 600 456 789',
    birthday: '30 January 2000',
    info: 'PPL online · Q4 2025',
  },
]
